export enum ActionType {
  //auth
  USER_LOADING = "USER_LOADING",
  USER_LOADED = "USER_LOADED",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
  LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
  AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS",
  AUTO_LOGIN = "AUTO_LOGIN",

  //static data
  LOAD_CUISINES = "LOAD_CUISINES",

  //Search
  RESTAURANT_SEARCH = "RESTAURANT_SEARCH",
  REST_LOAD_SUCCESS = "REST_LOAD_SUCCESS",
  SEARCH_LOADING = "SEARCH_LOADING",

  //restaurants
  LIKE_REST = "LIKE_REST",
  DIS_LIKE_REST = "DIS_LIKE_REST",
  LOAD_LIKES = "LOAD_LIKES"}