export enum ActionType {
  //auth
  USER_LOADING = "USER_LOADING",
  USER_LOADED = "USER_LOADED",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
  LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
  AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS",
  AUTO_LOGIN = "AUTO_LOGIN",
  USERNAME_SUCCESS = "USERNAME_SUCCESS",
  PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",

  //Deck
  ADD_DECK = "ADD_DECK",
  GET_DECKS = "GET_DECKS",

  SELECT_DECK = "SELECT_DECK",
  GET_DECK_FROM_FIREBASE = "GET_DECK_FROM_FIREBASE",
  GET_OPPONET_DECK_SUCCESS = "GET_OPPONET_DECK_SUCCESS",

  //Game
  START_GAME = "START_GAME",
  GAME_OVER = "GAME_OVER",
  SET_SCORE = "SET_SCORE",
  SET_GAME_HISTORY = "SET_GAME_HISTORY",
  END_GAME_RESET = "END_GAME_RESET",
  GAME_REMATCH = "GAME_REMATCH",
  GAME_OVER_ALERT = "GAME_OVER_ALERT"
}
